"""add_rating_and_favorite

Revision ID: 20dbff321163
Revises: 480e7856fecf
Create Date: 2026-04-17 10:01:53.781876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20dbff321163'
down_revision: Union[str, None] = '480e7856fecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_favorites_user_product')
    )
    op.add_column(
        'reviews',
        sa.Column('rating', sa.Integer(), nullable=False, server_default='5'),
    )
    op.alter_column('reviews', 'rating', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'rating')
    op.drop_table('favorites')
    # ### end Alembic commands ###
