"""add_stores_table_store_id_and_timestamps

Revision ID: 480e7856fecf
Revises: 1933401561f6
Create Date: 2026-04-16 00:24:45.380988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '480e7856fecf'
down_revision: Union[str, None] = '1933401561f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('addresses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('addresses', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('brands', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('brands', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cart_items', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cart_items', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_items', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # Step 1: Add store_id as nullable first (existing rows have no store)
    op.add_column('products', sa.Column('store_id', sa.String(length=36), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # Step 2: Insert a default placeholder store for existing products
    default_store_id = '00000000-0000-0000-0000-000000000000'
    op.execute(
        sa.text(
            "INSERT INTO stores (id, name, slug, email, password_hash, created_at, updated_at) "
            "VALUES (:id, :name, :slug, :email, :pw, NOW(), NOW())"
        ).bindparams(
            id=default_store_id,
            name='Default Store',
            slug='default-store',
            email='default@store.local',
            pw='placeholder',
        )
    )

    # Step 3: Backfill existing products with the default store
    op.execute(
        sa.text(
            "UPDATE products SET store_id = :sid WHERE store_id IS NULL"
        ).bindparams(sid=default_store_id)
    )

    # Step 4: Set store_id to NOT NULL and add FK constraint
    op.alter_column('products', 'store_id', nullable=False, existing_type=sa.String(length=36))
    op.create_foreign_key('fk_products_store_id', 'products', 'stores', ['store_id'], ['id'])
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'created_at')
    op.drop_constraint('fk_products_store_id', 'products', type_='foreignkey')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'store_id')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('order_items', 'updated_at')
    op.drop_column('order_items', 'created_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('cart_items', 'updated_at')
    op.drop_column('cart_items', 'created_at')
    op.drop_column('brands', 'updated_at')
    op.drop_column('brands', 'created_at')
    op.drop_column('addresses', 'updated_at')
    op.drop_column('addresses', 'created_at')
    op.drop_table('stores')
    # ### end Alembic commands ###
